$(document).ready(function(){
    $.getJSON(
        'https://wind-bow.gomix.me/twitch-api/streams/freecodecamp?callback=?',
        function(data){
            console.log(Array.from(data));
            Array.from(data).forEach(function(e){
                $(".list-group-item").append(e.toString());
            });
        });
});
